name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t mern-backend ./server

      - name: Build frontend image
        run: docker build -t mern-frontend ./Client

      # Optional: Login and push to Docker Hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push backend image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-backend

      # - name: Push frontend image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mern-frontend